export interface SeedNode {
  id: string;
  track: 'cs' | 'math';
  time_block: string;
  parent_id: string | null;
  title: string;
  resource_link: string | null;
  how_to_learn: string | null;
  sort_order: number;
}

export const seedData: SeedNode[] = [
  // ============================================================
  // CS TRACK — Summer Before Grade 11: Phases 0–1
  // ============================================================

  // -- Phase 0: DSA & Competitive Programming --
  {
    id: 'cs-phase-0',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Phase 0: DSA & Competitive Programming',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'cs-phase-0-silver-review',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Quick Silver review (two pointers, sliding window, hashing, basic graphs)',
    resource_link: 'https://usaco.guide/',
    how_to_learn: 'Skim fast. For anything not solid: timed reps on 1–2 problems, then spaced re-solve.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-0-graphs',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Graphs (Dijkstra, MST, topological sort)',
    resource_link: 'https://usaco.guide/',
    how_to_learn: 'Read → implement each algorithm from scratch before touching problems. Then timed reps on Gold problems. AI-assisted for edge cases.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-0-dp',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'DP (tree DP, bitmask DP, interval DP)',
    resource_link: 'https://usaco.guide/',
    how_to_learn: 'Do-first on each problem — minimum 30 min genuine attempt before editorial. Spaced re-solve a week later.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-0-greedy',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Greedy (exchange argument, common patterns)',
    resource_link: 'https://usaco.guide/',
    how_to_learn: 'Read → implement the exchange argument proof for each pattern, then timed reps.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-0-range-queries',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Range queries (segment trees, Fenwick trees)',
    resource_link: 'https://usaco.guide/',
    how_to_learn: 'Read → implement from scratch (no copy-paste). Build Fenwick tree by hand before segment trees. AI-assisted for index bugs only.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-0-number-theory',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Number theory (modular arithmetic, GCD, primes, combinatorics)',
    resource_link: null,
    how_to_learn: 'Read → implement each primitive (fast exp, sieve, modular inverse). Then apply in 1–2 contest problems.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-0-reference',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Reference: cp-algorithms.com',
    resource_link: 'https://cp-algorithms.com',
    how_to_learn: 'Read-only — look up when you hit an unfamiliar algorithm.',
    sort_order: 6,
  },
  {
    id: 'cs-phase-0-contest',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Contest practice (CCC/CCO past papers)',
    resource_link: 'https://cemc.uwaterloo.ca',
    how_to_learn: 'Timed reps — full contest conditions every other week. Spaced re-solve for editorial problems.',
    sort_order: 7,
  },
  {
    id: 'cs-phase-0-dmoj',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Online judge: DMOJ CCC archive',
    resource_link: 'https://dmoj.ca',
    how_to_learn: 'Timed reps + spaced re-solve for any problem that required an editorial.',
    sort_order: 8,
  },

  // -- Phase 1: Programming Fundamentals --
  {
    id: 'cs-phase-1',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Phase 1: Programming Fundamentals',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'cs-phase-1-cpp',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: 'C++ for competitive programming (syntax, STL, I/O, pointers, memory model)',
    resource_link: 'https://www.learncpp.com',
    how_to_learn: 'Type-along → variant through learncpp.com. Then timed reps on DMOJ with C++. AI-assisted for compiler errors.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-1-cs50p',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: 'Finish CS50P',
    resource_link: 'https://cs50.harvard.edu/python/',
    how_to_learn: 'Do-first on every problem set. Attempt cold, push through — then check.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-1-intermediate-python',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: 'Intermediate Python (comprehensions, generators, decorators, context managers, type hints)',
    resource_link: 'https://realpython.com',
    how_to_learn: 'Type-along → variant for each feature. After decorator tutorial, write your own timing decorator from scratch.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-1-oop',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: 'OOP in depth (inheritance vs. composition, basic SOLID)',
    resource_link: 'https://www.youtube.com/c/Coreyms',
    how_to_learn: 'Type-along → variant — rebuild example class from memory, then write a second one for different domain.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-1-git',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: 'Git (branching, merging, conflict resolution, PR workflow)',
    resource_link: 'https://git-scm.com/book',
    how_to_learn: 'Read → implement — read a chapter, then do it in a throwaway repo. Deliberately create merge conflicts.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-1-cli-linux',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: 'CLI & Linux (filesystem, permissions, piping, bash basics, SSH)',
    resource_link: 'https://missing.csail.mit.edu',
    how_to_learn: 'Do-first on every exercise. Use your actual terminal throughout.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-1-testing',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: 'Testing (pytest, basic TDD, mocking)',
    resource_link: 'https://www.obeythetestinggoat.com',
    how_to_learn: 'Type-along → variant — write the test before the implementation on every exercise.',
    sort_order: 6,
  },

  // ============================================================
  // CS TRACK — Grade 11: Phase 2
  // ============================================================
  {
    id: 'cs-phase-2',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: null,
    title: 'Phase 2: Backend Engineering',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'cs-phase-2-cs50w',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-2',
    title: 'Full-stack foundations: CS50W',
    resource_link: 'https://cs50.harvard.edu/web/',
    how_to_learn: 'Do-first on every project. Finish the project yourself before any walkthrough.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-2-http',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-2',
    title: 'HTTP (methods, status codes, headers, statelessness)',
    resource_link: 'https://developer.mozilla.org/en-US/docs/Web/HTTP',
    how_to_learn: 'Read-only + one experiment: use curl to manually send GET, POST, and bad request to a live API.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-2-fastapi',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-2',
    title: 'FastAPI (routing, Pydantic, dependency injection, async basics)',
    resource_link: 'https://fastapi.tiangolo.com/tutorial/',
    how_to_learn: 'Type-along → variant — after each section, build the same endpoint for a different resource from memory.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-2-postgresql',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-2',
    title: 'PostgreSQL deep dive (joins, indexes, transactions, normalization)',
    resource_link: 'https://sqlbolt.com',
    how_to_learn: 'Timed reps on SQLBolt and pgexercises. For schema design: do-first, then compare against normal form rules.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-2-sqlalchemy',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-2',
    title: 'SQLAlchemy ORM (models, migrations, queries)',
    resource_link: 'https://docs.sqlalchemy.org',
    how_to_learn: 'Type-along → variant — build a small model set, rebuild for a different domain. AI-assisted for Alembic errors.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-2-redis',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-2',
    title: 'Redis (caching, sessions, pub/sub basics)',
    resource_link: 'https://redis.io/docs/',
    how_to_learn: 'Type-along → variant — implement a cache-aside pattern manually in Python after the intro.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-2-auth',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-2',
    title: 'Auth (bcrypt, JWT, OAuth2 flow)',
    resource_link: 'https://fastapi.tiangolo.com/tutorial/security/',
    how_to_learn: 'Type-along → variant — implement full login + protected route, then rebuild from scratch in blank project.',
    sort_order: 6,
  },
  {
    id: 'cs-phase-2-background-tasks',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-2',
    title: 'Background tasks & queuing (Celery + Redis)',
    resource_link: 'https://docs.celeryq.dev/en/stable/getting-started/first-steps-with-celery.html',
    how_to_learn: 'Type-along → variant — get one background task working end-to-end, then add a second of your own design.',
    sort_order: 7,
  },
  {
    id: 'cs-phase-2-api-testing',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-2',
    title: 'API testing (pytest + httpx/TestClient)',
    resource_link: 'https://fastapi.tiangolo.com/tutorial/testing/',
    how_to_learn: 'Do-first — write tests before endpoints on at least one project.',
    sort_order: 8,
  },
  {
    id: 'cs-phase-2-practice',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-2',
    title: 'Practice reps: Build 3–4 small APIs (last one calls an LLM endpoint)',
    resource_link: null,
    how_to_learn: 'Do-first on all specs. AI-assisted only to get unstuck on specific errors, never to scaffold.',
    sort_order: 9,
  },

  // ============================================================
  // CS TRACK — Summer Before Grade 12: Phases 3–4
  // ============================================================

  // -- Phase 3: System Design --
  {
    id: 'cs-phase-3',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: null,
    title: 'Phase 3: System Design',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'cs-phase-3-core',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: 'cs-phase-3',
    title: 'Core concepts (load balancing, caching, CAP theorem, replication)',
    resource_link: 'https://github.com/donnemartin/system-design-primer',
    how_to_learn: 'Read → implement: read a concept, close it, write a half-page explanation in your own words.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-3-scaling',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: 'cs-phase-3',
    title: 'Scaling patterns (sharding, message queues, CDNs)',
    resource_link: 'https://www.youtube.com/@ByteByteGo',
    how_to_learn: 'Watch → draw the architecture from memory on paper before the next video.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-3-ddia',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: 'cs-phase-3',
    title: 'Deep dive: Designing Data-Intensive Applications (Kleppmann)',
    resource_link: null,
    how_to_learn: 'Read → implement (explain in your own words after each chapter). One chapter per sitting.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-3-practice',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: 'cs-phase-3',
    title: 'Practice: Design 3–4 classic systems on paper',
    resource_link: null,
    how_to_learn: 'Do-first — attempt a full design on paper before reading. AI-assisted to stress-test ("what breaks at 10M users?").',
    sort_order: 3,
  },

  // -- Phase 4: DevOps & Cloud --
  {
    id: 'cs-phase-4',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: null,
    title: 'Phase 4: DevOps & Cloud',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'cs-phase-4-docker',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: 'cs-phase-4',
    title: 'Docker (images, Dockerfile, docker-compose)',
    resource_link: 'https://docs.docker.com/get-started/',
    how_to_learn: 'Type-along → variant — containerize one of your Phase 2 APIs. Deliberately break something and debug.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-4-cicd',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: 'cs-phase-4',
    title: 'CI/CD pipelines (GitHub Actions)',
    resource_link: 'https://docs.github.com/en/actions',
    how_to_learn: 'Type-along → variant — get a pipeline running, then add a step you designed yourself. AI-assisted for YAML errors.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-4-deployment',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: 'cs-phase-4',
    title: 'First real deployment (Render.com or Railway)',
    resource_link: 'https://render.com',
    how_to_learn: 'Do-first — try to deploy without a tutorial first. Read docs only when you hit an error.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-4-cloud',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: 'cs-phase-4',
    title: 'Cloud fundamentals (AWS Cloud Practitioner Essentials)',
    resource_link: 'https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/',
    how_to_learn: 'Read-only for now — orientation, not skill-building.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-4-monitoring',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: 'cs-phase-4',
    title: 'Monitoring (logs, metrics, alerts)',
    resource_link: 'https://www.youtube.com/@freecodecamp',
    how_to_learn: 'Watch → code same day — add structured logging to one of your existing APIs that day.',
    sort_order: 4,
  },

  // ============================================================
  // CS TRACK — Grade 12: Phases 5–6
  // ============================================================

  // -- Phase 5: Math & Stats for ML --
  {
    id: 'cs-phase-5',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: null,
    title: 'Phase 5: Math & Stats for ML',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'cs-phase-5-algebra-trig',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-5',
    title: 'Algebra & trig fluency (Gr. 11 course)',
    resource_link: 'https://www.khanacademy.org',
    how_to_learn: 'Use Khan Academy only when a school topic feels shaky — timed reps on exercises for that topic.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-5-linear-algebra',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-5',
    title: 'Linear algebra (vectors, matrices, eigenvectors)',
    resource_link: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab',
    how_to_learn: 'Watch → code same day: implement the operation in NumPy after each video. Timed reps on Khan Academy.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-5-prob-stats',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-5',
    title: 'Probability & stats (distributions, Bayes, expectation/variance)',
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch → code same day: simulate the concept in Python after each video. Timed reps on Khan Academy.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-5-calculus',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-5',
    title: 'Calculus (derivatives, gradients, chain rule only)',
    resource_link: 'https://www.khanacademy.org/math/differential-calculus',
    how_to_learn: 'Read-only + exercises at a slow pace. Work every Khan Academy exercise. No rush.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-5-mml',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-5',
    title: 'Optional: Mathematics for Machine Learning (formal treatment)',
    resource_link: 'https://mml-book.github.io',
    how_to_learn: 'Read → implement — work the exercises, don\'t just read the derivations. Gr. 12 and beyond.',
    sort_order: 4,
  },

  // -- Phase 6: Classical ML --
  {
    id: 'cs-phase-6',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: null,
    title: 'Phase 6: Classical ML',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'cs-phase-6-cs50ai',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: 'Survey foundation: CS50 AI',
    resource_link: 'https://cs50.harvard.edu/ai/',
    how_to_learn: 'Do-first on every project. Implement minimax, naive Bayes, etc. yourself.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-6-ml-stack',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: 'Python ML stack (NumPy, Pandas, Matplotlib)',
    resource_link: 'https://www.kaggle.com/learn',
    how_to_learn: 'Type-along → variant — after each notebook, reproduce key operations on a different dataset from memory.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-6-ml-workflow',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: 'ML workflow (train/test split, cross-validation, metrics)',
    resource_link: 'https://www.kaggle.com/learn',
    how_to_learn: 'Type-along → variant — implement a full train/eval/test split pipeline from scratch after the tutorial.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-6-supervised',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: 'Supervised learning (linear/logistic regression, decision trees, XGBoost)',
    resource_link: null,
    how_to_learn: 'Read → implement — one algorithm per session with scikit-learn from scratch. AI-assisted to understand accuracy differences.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-6-unsupervised',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: 'Unsupervised learning (k-means, PCA)',
    resource_link: null,
    how_to_learn: 'Read → implement, then apply to a dataset of your own choosing.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-6-ng',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: 'Optional: Andrew Ng ML Specialization (Coursera)',
    resource_link: 'https://www.coursera.org/specializations/machine-learning-introduction',
    how_to_learn: 'Watch → code same day — do assignments before moving to the next lecture.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-6-kaggle',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: 'Kaggle practice (Titanic → tabular playground)',
    resource_link: 'https://www.kaggle.com/competitions',
    how_to_learn: 'Do-first — submit a baseline before reading public notebooks. Then incorporate one idea at a time.',
    sort_order: 6,
  },

  // ============================================================
  // CS TRACK — Summer After Grade 12: Phases 7–9 + Side Fields
  // ============================================================

  // -- Phase 7: Deep Learning --
  {
    id: 'cs-phase-7',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Phase 7: Deep Learning',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'cs-phase-7-nn-fundamentals',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-7',
    title: 'Neural net fundamentals (forward/backward pass, backprop intuition)',
    resource_link: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi',
    how_to_learn: 'Watch → code same day — implement a 2-layer net forward and backward pass in pure NumPy.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-7-pytorch',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-7',
    title: 'PyTorch (tensors, autograd, nn.Module, training loops)',
    resource_link: 'https://pytorch.org/tutorials/beginner/basics/intro.html',
    how_to_learn: 'Type-along → variant — rebuild same network for a different task from memory. AI-assisted for tensor shape errors.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-7-fastai',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-7',
    title: 'Practical top-down approach: fast.ai',
    resource_link: 'https://course.fast.ai',
    how_to_learn: 'Do-first on every notebook — run it, break something, fix it.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-7-cnn-rnn',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-7',
    title: 'CNNs / RNNs',
    resource_link: 'https://course.fast.ai',
    how_to_learn: 'Implement the architecture on a dataset you chose, not the one fast.ai uses.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-7-transformers',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-7',
    title: 'Transformers (attention mechanism)',
    resource_link: 'https://d2l.ai',
    how_to_learn: 'Watch 3B1B → code same day. Then read → implement scaled dot-product attention in PyTorch from d2l chapter.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-7-d2l',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-7',
    title: 'Optional textbook: Dive into Deep Learning (d2l.ai)',
    resource_link: 'https://d2l.ai',
    how_to_learn: 'Read → implement — run every notebook, then modify. Don\'t read without running code.',
    sort_order: 5,
  },

  // -- Phase 8: Applied AI / LLMs / MLOps --
  {
    id: 'cs-phase-8',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Phase 8: Applied AI / LLMs / MLOps',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'cs-phase-8-prompt-eng',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'Prompt engineering properly',
    resource_link: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview',
    how_to_learn: 'Read → implement — test each technique against a task you care about. Keep a log.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-8-structured-outputs',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'Structured outputs & function calling',
    resource_link: null,
    how_to_learn: 'Type-along → variant — get model returning structured JSON, then design your own schema.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-8-embeddings',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'Embeddings & vector DBs (pgvector, Chroma)',
    resource_link: 'https://huggingface.co/learn/nlp-course',
    how_to_learn: 'Type-along → variant — embed documents, store in pgvector, run similarity queries. Swap embedding model and compare.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-8-rag',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'RAG pipelines (end-to-end)',
    resource_link: 'https://www.deeplearning.ai',
    how_to_learn: 'Type-along → variant — get tutorial RAG pipeline working, then rebuild for your own domain.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-8-rag-eval',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'RAG evaluation (recall, precision, faithfulness)',
    resource_link: null,
    how_to_learn: 'Do-first — define "good retrieval" for your app before reading metrics. Then instrument with RAGAS.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-8-agents',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'Agents & tool use (multi-step LLM workflows, ReAct)',
    resource_link: 'https://www.deeplearning.ai',
    how_to_learn: 'Do-first after tutorial — design and build an agent that solves a task you defined.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-8-langgraph',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'Agentic frameworks (LangGraph or AutoGen)',
    resource_link: 'https://langchain-ai.github.io/langgraph/',
    how_to_learn: 'Type-along → variant — build tutorial graph, then design a second with loop and human-in-the-loop.',
    sort_order: 6,
  },
  {
    id: 'cs-phase-8-observability',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'Observability & tracing (LangSmith or Langfuse)',
    resource_link: null,
    how_to_learn: 'Type-along → variant — instrument one pipeline with tracing. You can\'t debug what you can\'t observe.',
    sort_order: 7,
  },
  {
    id: 'cs-phase-8-finetuning',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'Lightweight fine-tuning (LoRA/PEFT)',
    resource_link: 'https://huggingface.co/learn/nlp-course',
    how_to_learn: 'Type-along → variant — fine-tune on tutorial dataset, then on small dataset of your own.',
    sort_order: 8,
  },
  {
    id: 'cs-phase-8-mlops',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'MLOps (model serving, versioning, monitoring drift)',
    resource_link: 'https://madewithml.com',
    how_to_learn: 'Type-along → variant — follow serving tutorial, then add drift-detection of your own design.',
    sort_order: 9,
  },
  {
    id: 'cs-phase-8-cloud-ai',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'Cloud AI infra (GPU instances, managed serving)',
    resource_link: null,
    how_to_learn: 'Type-along → variant — deploy model end-to-end, then modify serving config. AI-assisted for IAM errors.',
    sort_order: 10,
  },
  {
    id: 'cs-phase-8-multimodal',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'Multimodal inputs (vision + text, document parsing)',
    resource_link: null,
    how_to_learn: 'Type-along → variant — build pipeline taking image/PDF as input, produce structured output.',
    sort_order: 11,
  },
  {
    id: 'cs-phase-8-capstone-tie',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-8',
    title: 'Capstone tie-in: Rebuild GPT wrapper as proper RAG app',
    resource_link: null,
    how_to_learn: 'Do-first — spec out rebuild yourself. Ship with RAGAS eval scores.',
    sort_order: 12,
  },

  // -- Phase 9: Capstone Projects --
  {
    id: 'cs-phase-9',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Phase 9: Capstone Projects',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'cs-phase-9-rag-app',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-9',
    title: 'RAG Q&A app (FastAPI + PostgreSQL + pgvector + React)',
    resource_link: null,
    how_to_learn: 'Do-first on full design. Ship v1 rough, add eval and tracing before calling it done.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-9-agentic',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-9',
    title: 'Agentic assistant (LangGraph + tool-calling + external APIs)',
    resource_link: null,
    how_to_learn: 'Do-first on agent design (tools, loop, failure modes, eval) before any code. Do it last — hardest project.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-9-ml-api',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-9',
    title: 'Classical ML API (scikit-learn/XGBoost + FastAPI + Docker)',
    resource_link: null,
    how_to_learn: 'Do-first — train and evaluate model before building the API. Most backend-heavy project.',
    sort_order: 2,
  },

  // -- Side Fields --
  {
    id: 'cs-side-fields',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Side Fields (~3%)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'cs-side-security',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-side-fields',
    title: 'App Security (PortSwigger Web Security Academy)',
    resource_link: 'https://portswigger.net/web-security',
    how_to_learn: 'Do-first on every lab. Find and fix one real vuln in your own API.',
    sort_order: 0,
  },
  {
    id: 'cs-side-data-eng',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-side-fields',
    title: 'Data Engineering (DataTalksClub Zoomcamp)',
    resource_link: 'https://github.com/DataTalksClub/data-engineering-zoomcamp',
    how_to_learn: 'Type-along → variant — build an Airflow pipeline for a data source you chose.',
    sort_order: 1,
  },
  {
    id: 'cs-side-networking',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-side-fields',
    title: 'Networking basics (Kurose & Ross, first 3 chapters)',
    resource_link: null,
    how_to_learn: 'Read-only for orientation; watch → code same day for sockets.',
    sort_order: 2,
  },
  {
    id: 'cs-side-frontend',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-side-fields',
    title: 'Frontend (React + TypeScript)',
    resource_link: 'https://scrimba.com/learn/learnreact',
    how_to_learn: 'Type-along → variant — build tutorial component, rebuild from memory. Dashboard UI for one capstone API.',
    sort_order: 3,
  },

  // ============================================================
  // MATH TRACK — Summer Before Grade 11
  // ============================================================

  // -- Block 1: MCR3U Functions --
  {
    id: 'math-summer11-mcr3u',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Block 1: MCR3U Functions (Days 1–30)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-summer11-mcr3u-functions',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Functions, domain/range, notation (Days 1–3)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Functions. Function composition mirrors programming functions.',
    sort_order: 0,
  },
  {
    id: 'math-summer11-mcr3u-transformations',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Transformations (shift, reflect, stretch) (Days 4–6)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Transformations. Activation function intuition later.',
    sort_order: 1,
  },
  {
    id: 'math-summer11-mcr3u-inverse',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Inverse functions (Days 7–8)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Inverse Functions. Critical for bijections in crypto/hashing.',
    sort_order: 2,
  },
  {
    id: 'math-summer11-mcr3u-quadratics-vertex',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Quadratics: vertex form, completing the square (Days 9–11)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Quadratics. Optimization intuition.',
    sort_order: 3,
  },
  {
    id: 'math-summer11-mcr3u-quadratic-formula',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Quadratic formula, discriminant (Days 12–13)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Quadratics.',
    sort_order: 4,
  },
  {
    id: 'math-summer11-mcr3u-polynomials',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Polynomial behaviour, factor/remainder theorem (Days 14–15)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Polynomials.',
    sort_order: 5,
  },
  {
    id: 'math-summer11-mcr3u-rational',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Rational functions, asymptotes (Days 16–17)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Rational Functions.',
    sort_order: 6,
  },
  {
    id: 'math-summer11-mcr3u-exponential',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Exponential functions — growth/decay, transformations (Days 18–21)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Exponential Functions. Prerequisite for learning rate schedules, sigmoid.',
    sort_order: 7,
  },
  {
    id: 'math-summer11-mcr3u-exp-equations',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Solving exponential equations (Days 22–23)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Exponential Equations.',
    sort_order: 8,
  },
  {
    id: 'math-summer11-mcr3u-trig-unit-circle',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Trig — unit circle, radians, CAST rule (Days 24–26)',
    resource_link: 'https://www.khanacademy.org/math/trigonometry',
    how_to_learn: 'Khan Academy — Trigonometry. Fourier transforms later; positional encoding in transformers.',
    sort_order: 9,
  },
  {
    id: 'math-summer11-mcr3u-trig-graphs',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Graphing sin/cos/tan, transformations (Days 27–28)',
    resource_link: 'https://www.khanacademy.org/math/trigonometry',
    how_to_learn: 'Khan Academy — Trig Graphs.',
    sort_order: 10,
  },
  {
    id: 'math-summer11-mcr3u-sine-cosine-law',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-mcr3u',
    title: 'Sine law, cosine law (Days 29–30)',
    resource_link: 'https://www.khanacademy.org/math/trigonometry',
    how_to_learn: 'Khan Academy — Trigonometry.',
    sort_order: 11,
  },

  // -- Block 2: Sequences & Series --
  {
    id: 'math-summer11-sequences',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Block 2: Sequences & Series (Days 31–40)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-summer11-seq-arithmetic',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-sequences',
    title: 'Arithmetic sequences & series (Days 31–33)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Sequences. Algorithm complexity intuition.',
    sort_order: 0,
  },
  {
    id: 'math-summer11-seq-geometric',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-sequences',
    title: 'Geometric sequences & series (Days 34–36)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Geometric Sequences. Gradient descent convergence.',
    sort_order: 1,
  },
  {
    id: 'math-summer11-seq-infinite',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-sequences',
    title: 'Infinite geometric series (Days 37–38)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy — Series. Neural net weight decay intuition.',
    sort_order: 2,
  },
  {
    id: 'math-summer11-seq-pascal',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-sequences',
    title: "Pascal's triangle, intro to combinatorics (Days 39–40)",
    resource_link: 'https://www.khanacademy.org/math/precalculus',
    how_to_learn: 'Khan Academy — Combinatorics. Probability foundation.',
    sort_order: 3,
  },

  // -- Block 3: Linear Algebra Start --
  {
    id: 'math-summer11-linalg',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Block 3: Linear Algebra Start (Days 41–65)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-summer11-linalg-vectors',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-linalg',
    title: 'Vectors — addition, scalar mult., dot product (Days 41–43)',
    resource_link: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab',
    how_to_learn: 'Watch 3B1B → implement in NumPy same day.',
    sort_order: 0,
  },
  {
    id: 'math-summer11-linalg-transforms',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-linalg',
    title: 'Linear transformations, matrix multiplication (Days 44–46)',
    resource_link: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab',
    how_to_learn: 'Watch 3B1B → build matrix multiply by hand, verify with np.dot.',
    sort_order: 1,
  },
  {
    id: 'math-summer11-linalg-determinants',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-linalg',
    title: 'Determinants (Days 47–49)',
    resource_link: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab',
    how_to_learn: 'Watch 3B1B → implement.',
    sort_order: 2,
  },
  {
    id: 'math-summer11-linalg-systems',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-linalg',
    title: 'Systems of equations, Gaussian elimination (Days 50–52)',
    resource_link: 'https://www.khanacademy.org/math/linear-algebra',
    how_to_learn: 'Read → solve a 3×3 system in pure Python.',
    sort_order: 3,
  },
  {
    id: 'math-summer11-linalg-inverse',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-linalg',
    title: 'Matrix inverse, rank, null space (Days 53–55)',
    resource_link: 'https://www.khanacademy.org/math/linear-algebra',
    how_to_learn: 'Watch/read → implement.',
    sort_order: 4,
  },
  {
    id: 'math-summer11-linalg-eigen',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-linalg',
    title: 'Eigenvectors & eigenvalues (Days 56–58)',
    resource_link: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab',
    how_to_learn: 'Watch 3B1B → find eigenvalues of 2×2 by hand, verify with np.linalg.eig.',
    sort_order: 5,
  },
  {
    id: 'math-summer11-linalg-pca',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-linalg',
    title: 'PCA intuition (Days 59–61)',
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch StatQuest → PCA on a toy 2D dataset in NumPy.',
    sort_order: 6,
  },
  {
    id: 'math-summer11-linalg-norms',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-linalg',
    title: 'Matrix norms, orthogonality, projections (Days 62–64)',
    resource_link: 'https://www.khanacademy.org/math/linear-algebra',
    how_to_learn: 'Read → implement.',
    sort_order: 7,
  },
  {
    id: 'math-summer11-linalg-review',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-summer11-linalg',
    title: 'Review & consolidation: Build mini linear algebra library (Day 65)',
    resource_link: null,
    how_to_learn: 'Build a mini linear algebra library in Python from scratch.',
    sort_order: 8,
  },

  // -- Block 4: Review & Buffer --
  {
    id: 'math-summer11-review',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Block 4: Review & Buffer (Days 66–70)',
    resource_link: null,
    how_to_learn: 'Catch-up days. Re-solve anything shaky. No new material.',
    sort_order: 3,
  },

  // ============================================================
  // MATH TRACK — Grade 11 School Year
  // ============================================================
  {
    id: 'math-grade11-prob-stats',
    track: 'math',
    time_block: 'grade-11',
    parent_id: null,
    title: 'Probability & Statistics (evenings, alongside school)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-grade11-counting',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Counting: permutations, combinations (Weeks 1–2)',
    resource_link: 'https://www.khanacademy.org/math/statistics-probability',
    how_to_learn: 'Timed reps on exercises.',
    sort_order: 0,
  },
  {
    id: 'math-grade11-basic-prob',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Basic probability: sample spaces, events, complement rule (Weeks 3–4)',
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch StatQuest → simulate in Python (flip coins, roll dice).',
    sort_order: 1,
  },
  {
    id: 'math-grade11-conditional',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Conditional probability, independence (Weeks 5–6)',
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch StatQuest → verify with Python simulations.',
    sort_order: 2,
  },
  {
    id: 'math-grade11-bayes',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: "Bayes' theorem (Weeks 7–8)",
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch StatQuest → write a Naive Bayes classifier from scratch.',
    sort_order: 3,
  },
  {
    id: 'math-grade11-discrete-dist',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Discrete distributions: Bernoulli, Binomial, Poisson (Weeks 9–10)',
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch StatQuest → simulate each distribution in NumPy.',
    sort_order: 4,
  },
  {
    id: 'math-grade11-continuous-dist',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Continuous distributions: Uniform, Normal/Gaussian (Weeks 11–12)',
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch StatQuest → sample, plot histograms, compute z-scores.',
    sort_order: 5,
  },
  {
    id: 'math-grade11-expectation',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Expectation, variance, standard deviation (Weeks 13–14)',
    resource_link: 'https://www.khanacademy.org/math/statistics-probability',
    how_to_learn: 'Read → implement by hand on small datasets.',
    sort_order: 6,
  },
  {
    id: 'math-grade11-clt',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Central Limit Theorem (Weeks 15–16)',
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch StatQuest → simulate: show CLT empirically in Python.',
    sort_order: 7,
  },
  {
    id: 'math-grade11-covariance',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Covariance, correlation (Weeks 17–18)',
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch StatQuest → correlation matrix in NumPy.',
    sort_order: 8,
  },
  {
    id: 'math-grade11-mle',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Maximum Likelihood Estimation (Weeks 19–20)',
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch StatQuest → MLE for a Gaussian by hand.',
    sort_order: 9,
  },
  {
    id: 'math-grade11-hypothesis',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Hypothesis testing, p-values (Weeks 21–22)',
    resource_link: 'https://www.youtube.com/@statquest',
    how_to_learn: 'Watch StatQuest → implement a t-test manually.',
    sort_order: 10,
  },
  {
    id: 'math-grade11-info-theory',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-grade11-prob-stats',
    title: 'Information theory basics: entropy, cross-entropy, KL divergence (Weeks 23–24)',
    resource_link: 'https://colah.github.io',
    how_to_learn: "Read Colah's blog → compute cross-entropy loss manually.",
    sort_order: 11,
  },

  // ============================================================
  // MATH TRACK — Summer Before Grade 12
  // ============================================================

  // -- Block 1: MHF4U Advanced Functions --
  {
    id: 'math-summer12-mhf4u',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: null,
    title: 'Block 1: MHF4U Advanced Functions Preview (Days 1–25)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-summer12-mhf4u-polynomials',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-mhf4u',
    title: 'Polynomial functions — graphs, end behaviour, multiplicity (Days 1–3)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy exercises.',
    sort_order: 0,
  },
  {
    id: 'math-summer12-mhf4u-dividing',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-mhf4u',
    title: 'Dividing polynomials, factor theorem review (Days 4–6)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy exercises.',
    sort_order: 1,
  },
  {
    id: 'math-summer12-mhf4u-rational',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-mhf4u',
    title: 'Rational functions — intercepts, asymptotes (Days 7–9)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy exercises.',
    sort_order: 2,
  },
  {
    id: 'math-summer12-mhf4u-logs',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-mhf4u',
    title: 'Logarithms — definition, laws, change of base (Days 10–12)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy exercises.',
    sort_order: 3,
  },
  {
    id: 'math-summer12-mhf4u-log-equations',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-mhf4u',
    title: 'Solving log equations, graphing log functions (Days 13–15)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy exercises.',
    sort_order: 4,
  },
  {
    id: 'math-summer12-mhf4u-exp-log',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-mhf4u',
    title: 'Exponential & log relationship (inverses) (Days 16–18)',
    resource_link: 'https://www.khanacademy.org/math/algebra2',
    how_to_learn: 'Khan Academy exercises.',
    sort_order: 5,
  },
  {
    id: 'math-summer12-mhf4u-trig-identities',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-mhf4u',
    title: 'Trig identities — Pythagorean, sum/difference (Days 19–21)',
    resource_link: 'https://www.khanacademy.org/math/trigonometry',
    how_to_learn: 'Khan Academy exercises.',
    sort_order: 6,
  },
  {
    id: 'math-summer12-mhf4u-trig-equations',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-mhf4u',
    title: 'Solving trig equations, general solutions (Days 22–24)',
    resource_link: 'https://www.khanacademy.org/math/trigonometry',
    how_to_learn: 'Khan Academy exercises.',
    sort_order: 7,
  },
  {
    id: 'math-summer12-mhf4u-review',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-mhf4u',
    title: 'Review (Day 25)',
    resource_link: null,
    how_to_learn: 'Review all topics.',
    sort_order: 8,
  },

  // -- Block 2: Calculus Entry Point --
  {
    id: 'math-summer12-calculus',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: null,
    title: 'Block 2: Calculus Entry Point (Days 26–55)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-summer12-calc-limits',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-calculus',
    title: 'Limits — intuition, limit laws (Days 26–28)',
    resource_link: 'https://www.khanacademy.org/math/differential-calculus',
    how_to_learn: 'Khan Academy. Foundation for derivatives.',
    sort_order: 0,
  },
  {
    id: 'math-summer12-calc-first-principles',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-calculus',
    title: 'Derivatives from first principles (Days 29–32)',
    resource_link: 'https://www.khanacademy.org/math/differential-calculus',
    how_to_learn: 'Khan Academy. Understanding what a gradient IS.',
    sort_order: 1,
  },
  {
    id: 'math-summer12-calc-rules',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-calculus',
    title: 'Differentiation rules: power, product, quotient (Days 33–35)',
    resource_link: 'https://www.khanacademy.org/math/differential-calculus',
    how_to_learn: 'Khan Academy exercises.',
    sort_order: 2,
  },
  {
    id: 'math-summer12-calc-chain-rule',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-calculus',
    title: 'Chain rule (Days 36–39) ⭐',
    resource_link: 'https://www.khanacademy.org/math/differential-calculus',
    how_to_learn: 'This IS backpropagation. Go slow. Master it.',
    sort_order: 3,
  },
  {
    id: 'math-summer12-calc-exp-log',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-calculus',
    title: 'Derivatives of exponentials & logs (eˣ, ln x) (Days 40–42)',
    resource_link: 'https://www.khanacademy.org/math/differential-calculus',
    how_to_learn: 'Khan Academy. Softmax, log-loss derivatives.',
    sort_order: 4,
  },
  {
    id: 'math-summer12-calc-trig',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-calculus',
    title: 'Derivatives of trig functions (Days 43–45)',
    resource_link: 'https://www.khanacademy.org/math/differential-calculus',
    how_to_learn: 'Khan Academy exercises.',
    sort_order: 5,
  },
  {
    id: 'math-summer12-calc-partial',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-calculus',
    title: 'Partial derivatives — intro (Days 46–48)',
    resource_link: 'https://www.khanacademy.org/math/multivariable-calculus',
    how_to_learn: 'Direct prerequisite for gradient descent in ML.',
    sort_order: 6,
  },
  {
    id: 'math-summer12-calc-gradients',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-calculus',
    title: 'Gradients & gradient vectors (Days 49–51)',
    resource_link: 'https://www.khanacademy.org/math/multivariable-calculus',
    how_to_learn: 'The math behind every optimizer (SGD, Adam).',
    sort_order: 7,
  },
  {
    id: 'math-summer12-calc-optimization',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-calculus',
    title: 'Optimization — critical points, 2nd derivative test (Days 52–54)',
    resource_link: 'https://www.khanacademy.org/math/differential-calculus',
    how_to_learn: 'Loss minimization intuition.',
    sort_order: 8,
  },
  {
    id: 'math-summer12-calc-review',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-calculus',
    title: 'Review (Day 55)',
    resource_link: null,
    how_to_learn: 'Review all calculus topics.',
    sort_order: 9,
  },

  // -- Block 3: Linear Algebra Completion + Multivariable --
  {
    id: 'math-summer12-linalg-adv',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: null,
    title: 'Block 3: Linear Algebra Completion + Multivariable (Days 56–70)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-summer12-jacobian',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-linalg-adv',
    title: 'Jacobian matrix intuition (Days 56–58)',
    resource_link: null,
    how_to_learn: 'Backprop through layers.',
    sort_order: 0,
  },
  {
    id: 'math-summer12-gradient-descent',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-linalg-adv',
    title: 'Gradient descent implemented in NumPy (Days 59–61)',
    resource_link: null,
    how_to_learn: 'Linear regression with gradient descent from scratch — no sklearn.',
    sort_order: 1,
  },
  {
    id: 'math-summer12-svd',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-linalg-adv',
    title: 'SVD intuition (Days 62–64)',
    resource_link: null,
    how_to_learn: 'Used in recommendation systems, compression.',
    sort_order: 2,
  },
  {
    id: 'math-summer12-vector-calc',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-linalg-adv',
    title: 'Vector calculus: gradient, divergence (Days 65–67)',
    resource_link: null,
    how_to_learn: 'Needed for understanding loss landscape.',
    sort_order: 3,
  },
  {
    id: 'math-summer12-backprop',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-summer12-linalg-adv',
    title: 'Backpropagation from scratch — derive mathematically (Days 68–70)',
    resource_link: null,
    how_to_learn: 'Implement a 2-layer net backward pass in pure NumPy.',
    sort_order: 4,
  },

  // ============================================================
  // MATH TRACK — Grade 12 School Year
  // ============================================================
  {
    id: 'math-grade12-ml-consolidation',
    track: 'math',
    time_block: 'grade-12',
    parent_id: null,
    title: 'Evening Math: ML Math Consolidation + CS Theory',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-grade12-multivariate-calc',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-grade12-ml-consolidation',
    title: 'Multivariate calculus — chain rule in matrix form, Jacobians (Sept–Oct)',
    resource_link: 'https://mml-book.github.io',
    how_to_learn: 'MML book. Read → implement.',
    sort_order: 0,
  },
  {
    id: 'math-grade12-optimization',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-grade12-ml-consolidation',
    title: 'Optimization theory — convexity, saddle points, Adam/momentum (Nov–Dec)',
    resource_link: 'https://mml-book.github.io',
    how_to_learn: 'MML book Ch. 7. Read → implement.',
    sort_order: 1,
  },
  {
    id: 'math-grade12-linalg-deep',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-grade12-ml-consolidation',
    title: 'Linear algebra deep dive — SVD, matrix factorization, spectral methods (Jan–Feb)',
    resource_link: 'https://mml-book.github.io',
    how_to_learn: 'MML book Ch. 2–4. Read → implement.',
    sort_order: 2,
  },
  {
    id: 'math-grade12-probability-formal',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-grade12-ml-consolidation',
    title: 'Probability theory formal — measure theory lite, conjugate priors (Mar–Apr)',
    resource_link: 'https://mml-book.github.io',
    how_to_learn: 'MML book Ch. 6. Read → implement.',
    sort_order: 3,
  },
  {
    id: 'math-grade12-info-theory-adv',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-grade12-ml-consolidation',
    title: 'Information theory — entropy, mutual information, KL divergence applications (May–Jun)',
    resource_link: null,
    how_to_learn: 'Elements of Information Theory Ch. 1–2. Read → implement.',
    sort_order: 4,
  },

  // ============================================================
  // MATH TRACK — Summer After Grade 12
  // ============================================================

  // -- Block 1: Deep Learning Math --
  {
    id: 'math-after12-dl-math',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Block 1: Deep Learning Math (Days 1–30)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-after12-backprop-deriv',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-dl-math',
    title: 'Backprop derivation — scalar → vector → matrix form (Days 1–5)',
    resource_link: null,
    how_to_learn: 'Phase 7: implement in pure NumPy.',
    sort_order: 0,
  },
  {
    id: 'math-after12-loss-functions',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-dl-math',
    title: 'Loss functions derived — MSE, cross-entropy, KL divergence (Days 6–10)',
    resource_link: null,
    how_to_learn: 'Why these functions, not others.',
    sort_order: 1,
  },
  {
    id: 'math-after12-activations',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-dl-math',
    title: 'Activation functions — sigmoid, tanh, ReLU, derivatives (Days 11–15)',
    resource_link: null,
    how_to_learn: 'Vanishing gradient problem — understand it mathematically.',
    sort_order: 2,
  },
  {
    id: 'math-after12-attention-math',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-dl-math',
    title: 'Attention mechanism math — scaled dot-product, softmax derivation (Days 16–20)',
    resource_link: null,
    how_to_learn: 'Phase 7: implement attention from scratch in PyTorch.',
    sort_order: 3,
  },
  {
    id: 'math-after12-conv-math',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-dl-math',
    title: 'Convolutional math — cross-correlation, filter math (Days 21–25)',
    resource_link: null,
    how_to_learn: 'CNN intuition.',
    sort_order: 4,
  },
  {
    id: 'math-after12-regularization',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-dl-math',
    title: 'Regularization math — L1/L2 as priors, dropout (Days 26–30)',
    resource_link: null,
    how_to_learn: 'Bayesian view of regularization.',
    sort_order: 5,
  },

  // -- Block 2: Advanced CS Math --
  {
    id: 'math-after12-cs-math',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Block 2: Advanced CS Math (Days 31–55)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-after12-combinatorics',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-cs-math',
    title: 'Combinatorics & counting — generating functions, recurrences (Days 31–35)',
    resource_link: null,
    how_to_learn: 'DSA: DP state counting, CCC problems.',
    sort_order: 0,
  },
  {
    id: 'math-after12-graph-theory',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-cs-math',
    title: 'Graph theory — trees, cycles, planarity (Days 36–40)',
    resource_link: null,
    how_to_learn: 'DSA: Phase 0 Gold topics.',
    sort_order: 1,
  },
  {
    id: 'math-after12-discrete',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-cs-math',
    title: 'Discrete math — logic, sets, relations, proofs (Days 41–45)',
    resource_link: null,
    how_to_learn: 'CS fundamentals, algorithm correctness.',
    sort_order: 2,
  },
  {
    id: 'math-after12-number-theory',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-cs-math',
    title: "Number theory — modular arithmetic, Fermat's little theorem, RSA (Days 46–50)",
    resource_link: null,
    how_to_learn: 'Cryptography in backend/security.',
    sort_order: 3,
  },
  {
    id: 'math-after12-bigo',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-cs-math',
    title: 'Big-O formal — asymptotic notation proofs, Master theorem (Days 51–55)',
    resource_link: null,
    how_to_learn: 'Analyzing your own algorithms rigorously.',
    sort_order: 4,
  },

  // -- Block 3: Applied ML Math --
  {
    id: 'math-after12-applied-ml',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Block 3: Applied ML Math (Days 56–70)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-after12-bayesian-ml',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-applied-ml',
    title: 'Bayesian ML — Bayesian linear regression, MAP estimation (Days 56–59)',
    resource_link: null,
    how_to_learn: 'Implement Bayesian linear regression.',
    sort_order: 0,
  },
  {
    id: 'math-after12-stat-learning',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-applied-ml',
    title: 'Statistical learning theory — bias-variance tradeoff, VC dimension (Days 60–63)',
    resource_link: null,
    how_to_learn: 'Formal understanding of bias-variance.',
    sort_order: 1,
  },
  {
    id: 'math-after12-embedding-math',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-applied-ml',
    title: 'Embedding math — vector spaces, cosine similarity derivation (Days 64–67)',
    resource_link: null,
    how_to_learn: 'Why dot product works for similarity.',
    sort_order: 2,
  },
  {
    id: 'math-after12-review-final',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-after12-applied-ml',
    title: 'Review + fill gaps from Phase 7–8 coding work (Days 68–70)',
    resource_link: null,
    how_to_learn: 'Review and fill any gaps identified during coding phases.',
    sort_order: 3,
  },
];
