export interface SeedNode {
  id: string;
  track: 'cs' | 'math';
  time_block: string;
  parent_id: string | null;
  title: string;
  resource_link: string | null;
  how_to_learn: string | null;
  sort_order: number;
}

export const seedData: SeedNode[] = [
  {
    id: 'cs-phase-0',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Phase 0: DSA & Competitive Programming',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'cs-phase-0-two-pointers-sliding-window-ha',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Two pointers, sliding window, hashing, recursion, sorting',
    resource_link: null,
    how_to_learn: 'Timed reps on 1–2 problems, then spaced re-solve.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-0-trees-bsts',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Trees & BSTs',
    resource_link: null,
    how_to_learn: 'Read → implement each traversal from scratch.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-0-bfs-dfs-graph-traversal',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'BFS / DFS, graph traversal',
    resource_link: null,
    how_to_learn: 'Read → implement BFS and DFS without reference. Timed reps on Silver graph problems.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-0-dijkstra-mst-kruskal-prim-topo',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Dijkstra, MST (Kruskal/Prim), topological sort',
    resource_link: null,
    how_to_learn: 'Read → implement each from scratch. AI-assisted for Dijkstra edge cases.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-0-dynamic-programming-1d-2d-tree',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Dynamic programming (1D/2D → tree DP, bitmask DP)',
    resource_link: null,
    how_to_learn: 'Do-first — 30 min minimum before the editorial. Spaced re-solve 1 week later.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-0-greedy-exchange-argument',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Greedy (exchange argument)',
    resource_link: null,
    how_to_learn: 'Read → implement.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-0-segment-trees-fenwick-trees',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Segment trees & Fenwick trees',
    resource_link: null,
    how_to_learn: 'Read → implement from scratch. Fenwick tree before segment trees.',
    sort_order: 6,
  },
  {
    id: 'cs-phase-0-number-theory-modular-arithmet',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Number theory (modular arithmetic, GCD, primes, combinatorics)',
    resource_link: null,
    how_to_learn: 'Read → implement each primitive (fast exp, sieve, modular inverse).',
    sort_order: 7,
  },
  {
    id: 'cs-phase-0-algorithm-reference',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Algorithm reference',
    resource_link: null,
    how_to_learn: 'Read-only — look up when you hit something unfamiliar.',
    sort_order: 8,
  },
  {
    id: 'cs-phase-0-contest-practice',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Contest practice',
    resource_link: null,
    how_to_learn: 'Timed reps every other week. Editorial only after a genuine attempt; spaced re-solve afterward.',
    sort_order: 9,
  },
  {
    id: 'cs-phase-0-online-judge',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-0',
    title: 'Online judge',
    resource_link: null,
    how_to_learn: 'Timed reps + spaced re-solve for problems that needed an editorial.',
    sort_order: 10,
  },
  {
    id: 'cs-phase-1',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Phase 1: Programming Fundamentals',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'cs-phase-1-c-for-competitive-programming-',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: '**C++ for competitive programming** — syntax, STL (vectors, maps, sets, priority queues), cin/cout, pointers, basic memory model',
    resource_link: null,
    how_to_learn: 'Type-along → variant through learncpp.com linearly. Timed reps on DMOJ in C++ immediately after basics. Target: Silver problems fluently in C++ within 3–4 weeks.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-1-finish-cs50p',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: '**Finish CS50P**',
    resource_link: null,
    how_to_learn: 'Do-first on every problem set.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-1-intermediate-python-comprehens',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: '**Intermediate Python** — comprehensions, generators, decorators, context managers, type hints, venv/poetry',
    resource_link: null,
    how_to_learn: 'Type-along → variant — after the decorator tutorial, write your own timing decorator from scratch.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-1-oop-in-depth-inheritance-vs-co',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: '**OOP in depth** — inheritance vs. composition, basic SOLID',
    resource_link: null,
    how_to_learn: 'Type-along → variant — rebuild each class from memory, then write a second for a different domain.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-1-git-for-real-branching-merging',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: '**Git for real** — branching, merging, conflict resolution, PR workflow',
    resource_link: null,
    how_to_learn: 'Read → implement. Deliberately create and resolve a merge conflict.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-1-cli-linux-basics-filesystem-pe',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: '**CLI & Linux basics** — filesystem, permissions, piping, bash scripting, SSH',
    resource_link: null,
    how_to_learn: 'Do-first on every exercise. Use your actual terminal.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-1-testing-pytest-tdd-basics-mock',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-1',
    title: '**Testing** — pytest, TDD basics, mocking',
    resource_link: null,
    how_to_learn: 'Type-along → variant — write the test before the implementation every time.',
    sort_order: 6,
  },
  {
    id: 'cs-phase-2',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Phase 2: Backend Engineering',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'cs-phase-2-full-stack-foundations-flask-d',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-2',
    title: '**Full-stack foundations** — Flask, Django, SQL, JS, APIs, security',
    resource_link: null,
    how_to_learn: 'Do-first on every project.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-2-http-methods-status-codes-head',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-2',
    title: '**HTTP** — methods, status codes, headers, statelessness',
    resource_link: null,
    how_to_learn: 'Read-only + experiment: use `curl` on a live API and read the raw responses.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-2-fastapi-routing-pydantic-model',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-2',
    title: '**FastAPI** — routing, Pydantic models, dependency injection, async',
    resource_link: null,
    how_to_learn: 'Type-along → variant — after each section, rebuild the endpoint for a different resource. AI-assisted for Pydantic errors.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-2-async-background-tasks-async-a',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-2',
    title: '**Async & background tasks** — `async`/`await`, BackgroundTasks, Celery',
    resource_link: null,
    how_to_learn: 'Type-along → variant — get one background task working end-to-end, then add one of your own design.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-2-postgresql-joins-indexes-trans',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-2',
    title: '**PostgreSQL** — joins, indexes, transactions, normalization, schema design',
    resource_link: null,
    how_to_learn: 'Timed reps on SQLBolt and pgexercises. Schema design: do-first.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-2-sqlalchemy-orm-models-migratio',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-2',
    title: '**SQLAlchemy ORM** — models, migrations, queries',
    resource_link: null,
    how_to_learn: 'Type-along → variant — build a model set, then rebuild for a different domain. AI-assisted for Alembic migration errors.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-2-redis-caching-sessions-pub-sub',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-2',
    title: '**Redis** — caching, sessions, pub/sub',
    resource_link: null,
    how_to_learn: 'Type-along → variant — implement a cache-aside pattern in Python.',
    sort_order: 6,
  },
  {
    id: 'cs-phase-2-auth-bcrypt-jwt-oauth2',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-2',
    title: '**Auth** — bcrypt, JWT, OAuth2',
    resource_link: null,
    how_to_learn: 'Type-along → variant — implement full login + protected route, then rebuild from scratch. AI-assisted to reason through the OAuth2 flow.',
    sort_order: 7,
  },
  {
    id: 'cs-phase-2-api-testing-pytest-httpx-testc',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-2',
    title: '**API testing** — pytest + httpx/TestClient',
    resource_link: null,
    how_to_learn: 'Do-first — write tests before endpoints on at least one project.',
    sort_order: 8,
  },
  {
    id: 'cs-phase-2-web-security-basics-owasp-top-',
    track: 'cs',
    time_block: 'summer-before-11',
    parent_id: 'cs-phase-2',
    title: '**Web security basics** — OWASP Top 10, CORS, HTTPS',
    resource_link: null,
    how_to_learn: 'Read-only. Hands-on in the App Security side field.',
    sort_order: 9,
  },
  {
    id: 'cs-phase-3',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: null,
    title: 'Phase 3: DevOps Lean Slice',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'cs-phase-3-docker-images-dockerfile-docke',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-3',
    title: '**Docker** — images, Dockerfile, docker-compose',
    resource_link: null,
    how_to_learn: 'Type-along → variant — containerize the finance tracker from last summer, then deliberately break something and debug it.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-3-ci-cd-pipelines',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-3',
    title: '**CI/CD pipelines**',
    resource_link: null,
    how_to_learn: 'Type-along → variant — get a pipeline running, then add a step you designed (linting, test coverage threshold). AI-assisted for YAML errors.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-3-first-real-deployment',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-3',
    title: '**First real deployment**',
    resource_link: null,
    how_to_learn: 'Do-first — try without a tutorial. Fix what breaks.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-3-cors-environment-variables',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-3',
    title: '**CORS & environment variables**',
    resource_link: null,
    how_to_learn: 'Read → implement when wiring your API to a frontend caller.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-3-structured-logging',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-3',
    title: '**Structured logging**',
    resource_link: null,
    how_to_learn: 'Type-along → variant — add structured JSON logging to your existing API the day you read about it.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-4',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: null,
    title: 'Phase 4: Applied AI & LLMs',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'cs-phase-4-prompt-engineering-chain-of-th',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-4',
    title: '**Prompt engineering** — chain-of-thought, few-shot, XML tags, system prompts',
    resource_link: null,
    how_to_learn: 'Read → implement after each technique. Keep a log of what worked.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-4-structured-outputs-function-ca',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-4',
    title: '**Structured outputs & function calling** — reliable JSON, tool use',
    resource_link: null,
    how_to_learn: 'Type-along → variant — get structured JSON working reliably, then design your own schema for a different use case.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-4-embeddings-vector-dbs-pgvector',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-4',
    title: '**Embeddings & vector DBs** — pgvector, Chroma',
    resource_link: null,
    how_to_learn: 'Type-along → variant — embed a small doc set in pgvector, run similarity queries, swap embedding models and compare.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-4-rag-pipelines-end-to-end',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-4',
    title: '**RAG pipelines end-to-end**',
    resource_link: null,
    how_to_learn: 'Type-along → variant — get the tutorial pipeline working, then rebuild for a domain you chose. AI-assisted to diagnose retrieval failures.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-4-rag-evaluation-recall-precisio',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-4',
    title: '**RAG evaluation** — recall, precision, faithfulness, answer relevance',
    resource_link: null,
    how_to_learn: 'Do-first — define what "good retrieval" means before reading the metrics. Then instrument with RAGAS.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-4-agents-tool-use-multi-step-llm',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-4',
    title: '**Agents & tool use** — multi-step LLM workflows, ReAct',
    resource_link: null,
    how_to_learn: 'Do-first after the tutorial — design and build an agent for a task you defined.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-4-agentic-frameworks-langgraph-s',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-4',
    title: '**Agentic frameworks** — LangGraph stateful graphs',
    resource_link: null,
    how_to_learn: 'Type-along → variant — build the tutorial graph, then design one with a loop and a human-in-the-loop step.',
    sort_order: 6,
  },
  {
    id: 'cs-phase-4-llm-observability-tracing-logg',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-4',
    title: '**LLM observability** — tracing, logging prompts/responses',
    resource_link: null,
    how_to_learn: 'Type-along → variant — instrument one pipeline. You can\'t debug what you can\'t observe.',
    sort_order: 7,
  },
  {
    id: 'cs-phase-4-ai-security-prompt-injection-d',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-phase-4',
    title: '**AI security** — prompt injection, data leakage in RAG, API key hygiene',
    resource_link: null,
    how_to_learn: 'Read → implement — audit your own RAG app for the top 3 risks.',
    sort_order: 8,
  },
  {
    id: 'cs-hackathon-toolkit',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: null,
    title: 'Hackathon Backend Toolkit',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'cs-hackathon-toolkit-api-scaffolding-first-2-hrs',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-hackathon-toolkit',
    title: 'API scaffolding (first 2 hrs):',
    resource_link: null,
    how_to_learn: 'Stand up FastAPI with CORS, env var handling, and `/health`. The AI engineer gets a base URL immediately and you iterate from there.',
    sort_order: 0,
  },
  {
    id: 'cs-hackathon-toolkit-async-endpoints',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-hackathon-toolkit',
    title: 'Async endpoints:',
    resource_link: null,
    how_to_learn: 'Every LLM-calling endpoint must be `async`. Use BackgroundTasks or Celery for anything that takes >2s — the frontend should never hang waiting on a model call.',
    sort_order: 1,
  },
  {
    id: 'cs-hackathon-toolkit-data-model-first-3-hrs',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-hackathon-toolkit',
    title: 'Data model (first 3 hrs):',
    resource_link: null,
    how_to_learn: 'Simple Postgres schema in docker-compose so everyone shares one connection string. Prevents the "we\'re all using different local SQLite files" disaster.',
    sort_order: 2,
  },
  {
    id: 'cs-hackathon-toolkit-ml-endpoint-if-genuinely-neede',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-hackathon-toolkit',
    title: 'ML endpoint if genuinely needed:',
    resource_link: null,
    how_to_learn: 'Only if the problem requires a real model (spam detection on structured features, a numeric classifier) — not for tasks an LLM handles. Use Hugging Face `pipeline()` or a pre-fitted sklearn model. Never train at the hackathon.',
    sort_order: 3,
  },
  {
    id: 'cs-internship-prep',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: null,
    title: 'Internship Preparation (Fall of Gr. 11)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 6,
  },
  {
    id: 'cs-internship-prep-finance-tracker-api',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-internship-prep',
    title: 'Finance tracker API',
    resource_link: null,
    how_to_learn: '— FastAPI, PostgreSQL, auth, testing, CI/CD, Docker, deployed',
    sort_order: 0,
  },
  {
    id: 'cs-internship-prep-document-q-a-api',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-internship-prep',
    title: 'Document Q&A API',
    resource_link: null,
    how_to_learn: '— RAG, pgvector, LLM integration, eval, tracing, deployed and documented',
    sort_order: 1,
  },
  {
    id: 'cs-internship-prep-one-open-source-contribution',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-internship-prep',
    title: 'One open-source contribution',
    resource_link: null,
    how_to_learn: '— even a documentation fix. Reading someone else\'s production codebase is a skill you can\'t build by only building your own projects.',
    sort_order: 2,
  },
  {
    id: 'cs-internship-prep-neetcode-150',
    track: 'cs',
    time_block: 'grade-11',
    parent_id: 'cs-internship-prep',
    title: 'NeetCode 150',
    resource_link: null,
    how_to_learn: '— start 3–4 weeks before applications, not now.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-internship',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: null,
    title: 'AI Internship (Summer after Gr. 11)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 7,
  },
  {
    id: 'cs-phase-internship-obs',
    track: 'cs',
    time_block: 'summer-before-12',
    parent_id: 'cs-phase-internship',
    title: 'Observe production RAG, eval pipelines, and model serving',
    resource_link: null,
    how_to_learn: 'Treat everything you observe as Phase 4/5 material happening in real time. Note every gap it exposes — those become Gr. 12 priorities.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-5',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: null,
    title: 'Phase 5: System Design & ML Systems',
    resource_link: null,
    how_to_learn: null,
    sort_order: 8,
  },
  {
    id: 'cs-phase-5-core-concepts-load-balancing-c',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-5',
    title: '**Core concepts** — load balancing, caching, CAP theorem, replication',
    resource_link: null,
    how_to_learn: 'Read → implement — after each concept, explain it in your own words. If you can\'t, you don\'t know it yet.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-5-scaling-patterns-sharding-mess',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-5',
    title: '**Scaling patterns** — sharding, message queues (Kafka/RabbitMQ), CDNs',
    resource_link: null,
    how_to_learn: 'Watch, then draw the architecture from memory before the next video. No drawing = no retention.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-5-deep-dive',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-5',
    title: '**Deep dive**',
    resource_link: null,
    how_to_learn: 'Read → implement. One chapter per sitting.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-5-ml-systems-design-training-pip',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-5',
    title: '**ML systems design** — training pipelines, feature stores, model registries, serving infra',
    resource_link: null,
    how_to_learn: 'Read → implement. The ML-specific extension that general system design books miss entirely.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-5-practice',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-5',
    title: '**Practice**',
    resource_link: null,
    how_to_learn: 'Do-first — full design on paper before reading Xu\'s chapter. AI-assisted to stress-test ("what breaks at 10M users?") afterward.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-6',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: null,
    title: 'Phase 6: Classical Machine Learning',
    resource_link: null,
    how_to_learn: null,
    sort_order: 9,
  },
  {
    id: 'cs-phase-6-survey-foundation-search-algor',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: '**Survey foundation** — search algorithms, classical ML, intro neural nets',
    resource_link: null,
    how_to_learn: 'Do-first on every project — implementing minimax, naive Bayes yourself is where the learning is.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-6-python-ml-stack-numpy-pandas-m',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: '**Python ML stack** — NumPy, Pandas, Matplotlib, seaborn',
    resource_link: null,
    how_to_learn: 'Type-along → variant — reproduce key operations on a different dataset from memory.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-6-ml-workflow-train-test-split-c',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: '**ML workflow** — train/test split, cross-validation, metrics (precision/recall/AUC)',
    resource_link: null,
    how_to_learn: 'Type-along → variant — implement a full pipeline from scratch after the tutorial, not during it.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-6-supervised-learning-linear-log',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: '**Supervised learning** — linear/logistic regression, decision trees, random forests, gradient boosting (XGBoost/LightGBM)',
    resource_link: null,
    how_to_learn: 'Read → implement one algorithm per session. AI-assisted to understand why accuracy differs, not to fix code.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-6-feature-engineering',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: '**Feature engineering**',
    resource_link: null,
    how_to_learn: 'Read → implement.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-6-unsupervised-learning-k-means-',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: '**Unsupervised learning** — k-means, PCA, UMAP',
    resource_link: null,
    how_to_learn: 'Implement, then apply to a dataset you chose.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-6-experiment-tracking-log-hyperp',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: '**Experiment tracking** — log hyperparameters, metrics, artifacts',
    resource_link: null,
    how_to_learn: 'Instrument every training run from this point forward. Habit matters more than the tool.',
    sort_order: 6,
  },
  {
    id: 'cs-phase-6-model-interpretability-shap-va',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: '**Model interpretability** — SHAP values',
    resource_link: null,
    how_to_learn: 'Read → implement — run SHAP on your Kaggle competition model.',
    sort_order: 7,
  },
  {
    id: 'cs-phase-6-optional',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: '**Optional**',
    resource_link: null,
    how_to_learn: 'Watch → code same day if you use it.',
    sort_order: 8,
  },
  {
    id: 'cs-phase-6-kaggle-practice',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-6',
    title: '**Kaggle practice**',
    resource_link: null,
    how_to_learn: 'Do-first — baseline submission before reading any public notebooks. Incorporate one idea at a time.',
    sort_order: 9,
  },
  {
    id: 'cs-phase-7',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: null,
    title: 'Phase 7: Deep Learning',
    resource_link: null,
    how_to_learn: null,
    sort_order: 10,
  },
  {
    id: 'cs-phase-7-neural-net-fundamentals-forwar',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-7',
    title: '**Neural net fundamentals** — forward/backward pass, backprop',
    resource_link: null,
    how_to_learn: 'Watch → code same day — implement a 2-layer net forward and backward pass in pure NumPy. Highest-leverage exercise in this phase.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-7-pytorch-tensors-autograd-nn-mo',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-7',
    title: '**PyTorch** — tensors, autograd, `nn.Module`, training loops, data loaders',
    resource_link: null,
    how_to_learn: 'Type-along → variant — rebuild the network for a different task from memory. AI-assisted for tensor shape errors.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-7-top-down-approach',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-7',
    title: '**Top-down approach**',
    resource_link: null,
    how_to_learn: 'Do-first on every notebook — run it, break something intentionally, fix it.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-7-transfer-learning-pre-trained-',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-7',
    title: '**Transfer learning** — pre-trained weights, fine-tuning',
    resource_link: null,
    how_to_learn: 'Type-along → variant — fine-tune on the tutorial dataset, then on a small custom dataset.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-7-cnns',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-7',
    title: '**CNNs**',
    resource_link: null,
    how_to_learn: 'Implement on a dataset you chose, not the one fast.ai uses.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-7-transformers-attention-encoder',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-7',
    title: '**Transformers** — attention, encoder/decoder; Karpathy\'s "Let\'s build GPT"',
    resource_link: null,
    how_to_learn: 'Watch → code same day for 3B1B. Implement scaled dot-product attention in PyTorch before using `nn.MultiheadAttention`.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-7-experiment-tracking-for-dl',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-7',
    title: '**Experiment tracking for DL**',
    resource_link: null,
    how_to_learn: 'Log every training run. Same habit, different context.',
    sort_order: 6,
  },
  {
    id: 'cs-phase-7-optional',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-7',
    title: '**Optional**',
    resource_link: null,
    how_to_learn: 'Read → implement every chapter\'s notebook, then modify.',
    sort_order: 7,
  },
  {
    id: 'cs-phase-8',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: null,
    title: 'Phase 8: DevOps Cloud Slice + MLOps',
    resource_link: null,
    how_to_learn: null,
    sort_order: 11,
  },
  {
    id: 'cs-phase-8-cloud-deployment-on-aws-elasti',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-8',
    title: '**Cloud deployment on AWS** — Elastic Beanstalk or App Runner, IAM basics',
    resource_link: null,
    how_to_learn: 'Type-along → variant — deploy an existing API to AWS, then modify the config. AI-assisted for IAM errors.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-8-managed-ml-platforms-training-',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-8',
    title: '**Managed ML platforms** — training endpoints, batch inference, managed serving',
    resource_link: null,
    how_to_learn: 'Type-along → variant — deploy a model end-to-end, then modify the serving config.',
    sort_order: 1,
  },
  {
    id: 'cs-phase-8-gpu-instances-gpu-vs-cpu-trade',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-8',
    title: '**GPU instances** — GPU vs. CPU tradeoffs, spot instances',
    resource_link: null,
    how_to_learn: 'Read-only + one experiment: run a small training job on a spot instance.',
    sort_order: 2,
  },
  {
    id: 'cs-phase-8-mlops-model-serving-versioning',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-8',
    title: '**MLOps** — model serving, versioning, monitoring drift',
    resource_link: null,
    how_to_learn: 'Type-along → variant — follow the serving tutorial, then add a drift-detection check of your own design.',
    sort_order: 3,
  },
  {
    id: 'cs-phase-8-lightweight-fine-tuning-at-sca',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-8',
    title: '**Lightweight fine-tuning at scale** — LoRA/PEFT',
    resource_link: null,
    how_to_learn: 'Type-along → variant — fine-tune with LoRA, then compare training time and performance against full fine-tuning from Phase 7.',
    sort_order: 4,
  },
  {
    id: 'cs-phase-8-llm-evaluation-building-real-e',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-8',
    title: '**LLM evaluation** — building real evals',
    resource_link: null,
    how_to_learn: 'Do-first — define what "good" means for your Phase 4 RAG app, then instrument it.',
    sort_order: 5,
  },
  {
    id: 'cs-phase-8-data-pipelines-for-ml-batch-et',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-8',
    title: '**Data pipelines for ML** — batch ETL feeding a training run',
    resource_link: null,
    how_to_learn: 'Type-along → variant — get the tutorial DAG running, then build one for a data source you chose.',
    sort_order: 6,
  },
  {
    id: 'cs-phase-capstone',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: null,
    title: 'Capstone: Agentic Assistant',
    resource_link: null,
    how_to_learn: null,
    sort_order: 12,
  },
  {
    id: 'cs-phase-capstone-project',
    track: 'cs',
    time_block: 'grade-12',
    parent_id: 'cs-phase-capstone',
    title: '🔨 Project — LangGraph multi-step agent with FastAPI backend',
    resource_link: null,
    how_to_learn: 'Draw the full agent graph (nodes, edges, loops, failure modes) on paper before writing any code. Write the eval harness before the agent logic. Stack: LangGraph, FastAPI, PostgreSQL, LangSmith.',
    sort_order: 0,
  },
  {
    id: 'cs-phase-summer12',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Summer after Gr. 12 Plans',
    resource_link: null,
    how_to_learn: null,
    sort_order: 13,
  },
  {
    id: 'cs-phase-summer12-plans',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-phase-summer12',
    title: 'Internship, independent project, or research before university',
    resource_link: null,
    how_to_learn: 'The backend work grounds core CS courses; the ML engineering work puts you ahead in ML/AI courses; experiment tracking habits read well to research labs.',
    sort_order: 0,
  },
  {
    id: 'cs-side-fields',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Side Fields (~4%)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 14,
  },
  {
    id: 'cs-side-fields-app-security',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-side-fields',
    title: '**App Security**',
    resource_link: null,
    how_to_learn: 'Do-first on every lab — attempt to exploit before reading the hint.. Project/Outcome: Find and fix one real vuln in your own deployed API before the internship application.',
    sort_order: 0,
  },
  {
    id: 'cs-side-fields-frontend-react-typescript',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-side-fields',
    title: '**Frontend (React + TypeScript)**',
    resource_link: null,
    how_to_learn: 'Type-along → variant — build the tutorial component, then rebuild from memory for a different use case.. Project/Outcome: A minimal frontend for the Gr. 11 Document Q&A API — just enough to demo without Postman.',
    sort_order: 1,
  },
  {
    id: 'cs-side-fields-networking-basics',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-side-fields',
    title: '**Networking basics**',
    resource_link: null,
    how_to_learn: 'Read-only. Project/Outcome: Understand what happens when your RAG app makes an API call; useful for debugging latency.',
    sort_order: 2,
  },
  {
    id: 'cs-side-fields-technical-writing',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-side-fields',
    title: '**Technical writing**',
    resource_link: null,
    how_to_learn: 'Read → implement for a real project. Project/Outcome: Proper README + OpenAPI docs for one deployed project.',
    sort_order: 3,
  },
  {
    id: 'cs-side-fields-open-source-contributing',
    track: 'cs',
    time_block: 'summer-after-12',
    parent_id: 'cs-side-fields',
    title: '**Open source contributing**',
    resource_link: null,
    how_to_learn: 'Read the codebase, find a real issue — even a documentation fix. Project/Outcome: One merged PR. Reading someone else\'s production codebase is a skill you can\'t build by only building your own projects.',
    sort_order: 4,
  },
  {
    id: 'math-sb11-mcr3u-functions',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Block 1: MCR3U: Functions (Days 1–30)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-sb11-mcr3u-functions-functions-domain-range-notatio',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '1–3: Functions, domain/range, notation',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-sb11-mcr3u-functions-transformations-shift-reflect-',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '4–6: Transformations (shift, reflect, stretch)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-sb11-mcr3u-functions-inverse-functions',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '7–8: Inverse functions',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-sb11-mcr3u-functions-quadratics-vertex-form-complet',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '9–11: Quadratics: vertex form, completing the square',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-sb11-mcr3u-functions-quadratic-formula-discriminant',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '12–13: Quadratic formula, discriminant',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-sb11-mcr3u-functions-polynomial-behaviour-factor-re',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '14–15: Polynomial behaviour, factor/remainder theorem',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'math-sb11-mcr3u-functions-rational-functions-asymptotes',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '16–17: Rational functions, asymptotes',
    resource_link: null,
    how_to_learn: null,
    sort_order: 6,
  },
  {
    id: 'math-sb11-mcr3u-functions-exponential-functions-growth-d',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '18–21: Exponential functions — growth/decay, transformations',
    resource_link: null,
    how_to_learn: null,
    sort_order: 7,
  },
  {
    id: 'math-sb11-mcr3u-functions-solving-exponential-equations',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '22–23: Solving exponential equations',
    resource_link: null,
    how_to_learn: null,
    sort_order: 8,
  },
  {
    id: 'math-sb11-mcr3u-functions-trig-unit-circle-radians-cast-',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '24–26: Trig — unit circle, radians, CAST rule',
    resource_link: null,
    how_to_learn: null,
    sort_order: 9,
  },
  {
    id: 'math-sb11-mcr3u-functions-graphing-sin-cos-tan-transform',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '27–28: Graphing sin/cos/tan, transformations',
    resource_link: null,
    how_to_learn: null,
    sort_order: 10,
  },
  {
    id: 'math-sb11-mcr3u-functions-sine-law-cosine-law',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-mcr3u-functions',
    title: '29–30: Sine law, cosine law',
    resource_link: null,
    how_to_learn: null,
    sort_order: 11,
  },
  {
    id: 'math-sb11-sequences-series',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Block 2: Sequences & Series (Days 31–40)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-sb11-sequences-series-arithmetic-sequences-series',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-sequences-series',
    title: '31–33: Arithmetic sequences & series',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-sb11-sequences-series-geometric-sequences-series',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-sequences-series',
    title: '34–36: Geometric sequences & series',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-sb11-sequences-series-infinite-geometric-series',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-sequences-series',
    title: '37–38: Infinite geometric series',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-sb11-sequences-series-pascal-s-triangle-intro-to-com',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-sequences-series',
    title: '39–40: Pascal\'s triangle, intro to combinatorics',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-sb11-linear-algebra-start',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Block 3: Linear Algebra Start (Days 41–65)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-sb11-linear-algebra-start-vectors-addition-scalar-mult-d',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-linear-algebra-start',
    title: '41–43: Vectors — addition, scalar mult., dot product',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-sb11-linear-algebra-start-linear-transformations-matrix-',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-linear-algebra-start',
    title: '44–46: Linear transformations, matrix multiplication',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-sb11-linear-algebra-start-determinants',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-linear-algebra-start',
    title: '47–49: Determinants',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-sb11-linear-algebra-start-systems-of-equations-gaussian-',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-linear-algebra-start',
    title: '50–52: Systems of equations, Gaussian elimination',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-sb11-linear-algebra-start-matrix-inverse-rank-null-space',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-linear-algebra-start',
    title: '53–55: Matrix inverse, rank, null space',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-sb11-linear-algebra-start-eigenvectors-eigenvalues',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-linear-algebra-start',
    title: '56–58: Eigenvectors & eigenvalues',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'math-sb11-linear-algebra-start-pca-intuition-eigenvectors-app',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-linear-algebra-start',
    title: '59–61: PCA intuition (eigenvectors applied)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 6,
  },
  {
    id: 'math-sb11-linear-algebra-start-matrix-norms-orthogonality-pro',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-linear-algebra-start',
    title: '62–64: Matrix norms, orthogonality, projections',
    resource_link: null,
    how_to_learn: null,
    sort_order: 7,
  },
  {
    id: 'math-sb11-linear-algebra-start-review-consolidation',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: 'math-sb11-linear-algebra-start',
    title: '65: Review & consolidation',
    resource_link: null,
    how_to_learn: null,
    sort_order: 8,
  },
  {
    id: 'math-sb11-review-buffer',
    track: 'math',
    time_block: 'summer-before-11',
    parent_id: null,
    title: 'Block 4: Review & Buffer (Days 66–70)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-gr11-school-mcr3u',
    track: 'math',
    time_block: 'grade-11',
    parent_id: null,
    title: 'School — MCR3U (JensenMath)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-gr11-school-mcr3u-unit-1',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-school-mcr3u',
    title: 'Unit 1: Unit 1',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-gr11-school-mcr3u-unit-2',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-school-mcr3u',
    title: 'Unit 2: Unit 2',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-gr11-school-mcr3u-unit-3',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-school-mcr3u',
    title: 'Unit 3: Unit 3',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-gr11-school-mcr3u-unit-4',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-school-mcr3u',
    title: 'Unit 4: Unit 4',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-gr11-school-mcr3u-unit-5',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-school-mcr3u',
    title: 'Unit 5: Unit 5',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-gr11-school-mcr3u-unit-6',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-school-mcr3u',
    title: 'Unit 6: Unit 6',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'math-gr11-school-mcr3u-unit-7',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-school-mcr3u',
    title: 'Unit 7: Unit 7',
    resource_link: null,
    how_to_learn: null,
    sort_order: 6,
  },
  {
    id: 'math-gr11-school-mcr3u-exam',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-school-mcr3u',
    title: 'Exam: Exam',
    resource_link: null,
    how_to_learn: null,
    sort_order: 7,
  },
  {
    id: 'math-gr11-evenings-probability-statistic',
    track: 'math',
    time_block: 'grade-11',
    parent_id: null,
    title: 'Evenings — Probability & Statistics',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-counting-permutations-combinat',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '1–2: Counting: permutations, combinations',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-basic-probability-sample-space',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '3–4: Basic probability: sample spaces, events, complement rule',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-conditional-probability-indepe',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '5–6: Conditional probability, independence',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-bayes-theorem',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '7–8: Bayes\' theorem',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-discrete-distributions-bernoul',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '9–10: Discrete distributions: Bernoulli, Binomial, Poisson',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-continuous-distributions-unifo',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '11–12: Continuous distributions: Uniform, Normal (Gaussian)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-expectation-variance-standard-',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '13–14: Expectation, variance, standard deviation',
    resource_link: null,
    how_to_learn: null,
    sort_order: 6,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-central-limit-theorem',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '15–16: Central Limit Theorem',
    resource_link: null,
    how_to_learn: null,
    sort_order: 7,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-covariance-correlation',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '17–18: Covariance, correlation',
    resource_link: null,
    how_to_learn: null,
    sort_order: 8,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-maximum-likelihood-estimation-',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '19–20: Maximum Likelihood Estimation (MLE)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 9,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-hypothesis-testing-p-values-co',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '21–22: Hypothesis testing, p-values (conceptual)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 10,
  },
  {
    id: 'math-gr11-evenings-probability-statistic-information-theory-basics-entr',
    track: 'math',
    time_block: 'grade-11',
    parent_id: 'math-gr11-evenings-probability-statistic',
    title: '23–24: Information theory basics: entropy, cross-entropy, KL divergence',
    resource_link: null,
    how_to_learn: null,
    sort_order: 11,
  },
  {
    id: 'math-sb12-mhf4u-advanced-functions',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: null,
    title: 'Block 1: MHF4U: Advanced Functions (Days 1–25)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 6,
  },
  {
    id: 'math-sb12-mhf4u-advanced-functions-polynomial-functions-graphs-en',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-mhf4u-advanced-functions',
    title: '1–3: Polynomial functions — graphs, end behaviour, multiplicity of roots',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-sb12-mhf4u-advanced-functions-dividing-polynomials-factor-th',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-mhf4u-advanced-functions',
    title: '4–6: Dividing polynomials, factor theorem review',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-sb12-mhf4u-advanced-functions-rational-functions-intercepts-',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-mhf4u-advanced-functions',
    title: '7–9: Rational functions — intercepts, asymptotes (vertical, horizontal, oblique)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-sb12-mhf4u-advanced-functions-logarithms-definition-laws-cha',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-mhf4u-advanced-functions',
    title: '10–12: Logarithms — definition, laws, change of base',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-sb12-mhf4u-advanced-functions-solving-log-equations-graphing',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-mhf4u-advanced-functions',
    title: '13–15: Solving log equations, graphing log functions',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-sb12-mhf4u-advanced-functions-exponential-log-relationship-i',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-mhf4u-advanced-functions',
    title: '16–18: Exponential & log relationship (inverses)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'math-sb12-mhf4u-advanced-functions-trig-identities-pythagorean-su',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-mhf4u-advanced-functions',
    title: '19–21: Trig identities — Pythagorean, sum/difference formulas',
    resource_link: null,
    how_to_learn: null,
    sort_order: 6,
  },
  {
    id: 'math-sb12-mhf4u-advanced-functions-solving-trig-equations-general',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-mhf4u-advanced-functions',
    title: '22–24: Solving trig equations, general solutions',
    resource_link: null,
    how_to_learn: null,
    sort_order: 7,
  },
  {
    id: 'math-sb12-mhf4u-advanced-functions-review',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-mhf4u-advanced-functions',
    title: '25: Review',
    resource_link: null,
    how_to_learn: null,
    sort_order: 8,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: null,
    title: 'Block 2: Calculus Entry Point / MCV4U Preview (Days 26–55)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 7,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre-limits-intuition-limit-laws',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    title: '26–28: Limits — intuition, limit laws',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre-derivatives-from-first-princip',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    title: '29–32: Derivatives from first principles',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre-differentiation-rules-power-pr',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    title: '33–35: Differentiation rules: power, product, quotient',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre-chain-rule',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    title: '36–39: Chain rule',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre-derivatives-of-exponentials-lo',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    title: '40–42: Derivatives of exponentials & logs (eˣ, ln x)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre-derivatives-of-trig-functions',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    title: '43–45: Derivatives of trig functions',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre-partial-derivatives-intro',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    title: '46–48: Partial derivatives — intro',
    resource_link: null,
    how_to_learn: null,
    sort_order: 6,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre-gradients-gradient-vectors',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    title: '49–51: Gradients & gradient vectors',
    resource_link: null,
    how_to_learn: null,
    sort_order: 7,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre-optimization-critical-points-2',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    title: '52–54: Optimization — critical points, 2nd derivative test',
    resource_link: null,
    how_to_learn: null,
    sort_order: 8,
  },
  {
    id: 'math-sb12-calculus-entry-point-mcv4u-pre-review',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-calculus-entry-point-mcv4u-pre',
    title: '55: Review',
    resource_link: null,
    how_to_learn: null,
    sort_order: 9,
  },
  {
    id: 'math-sb12-linear-algebra-completion-mult',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: null,
    title: 'Block 3: Linear Algebra Completion + Multivariable (Days 56–70)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 8,
  },
  {
    id: 'math-sb12-linear-algebra-completion-mult-jacobian-matrix-intuition',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-linear-algebra-completion-mult',
    title: '56–58: Jacobian matrix intuition',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-sb12-linear-algebra-completion-mult-gradient-descent-implemented-i',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-linear-algebra-completion-mult',
    title: '59–61: Gradient descent implemented in NumPy',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-sb12-linear-algebra-completion-mult-svd-intuition-singular-value-d',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-linear-algebra-completion-mult',
    title: '62–64: SVD intuition (Singular Value Decomposition)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-sb12-linear-algebra-completion-mult-vector-calculus-gradient-diver',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-linear-algebra-completion-mult',
    title: '65–67: Vector calculus: gradient, divergence (light)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-sb12-linear-algebra-completion-mult-backpropagation-from-scratch-d',
    track: 'math',
    time_block: 'summer-before-12',
    parent_id: 'math-sb12-linear-algebra-completion-mult',
    title: '68–70: Backpropagation from scratch — derive it mathematically',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-gr12-school-mhf4u-advanced-function',
    track: 'math',
    time_block: 'grade-12',
    parent_id: null,
    title: 'School — MHF4U Advanced Functions (JensenMath)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 9,
  },
  {
    id: 'math-gr12-school-mhf4u-advanced-function-unit-1',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mhf4u-advanced-function',
    title: 'Unit 1: Unit 1',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-gr12-school-mhf4u-advanced-function-unit-2',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mhf4u-advanced-function',
    title: 'Unit 2: Unit 2',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-gr12-school-mhf4u-advanced-function-unit-3',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mhf4u-advanced-function',
    title: 'Unit 3: Unit 3',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-gr12-school-mhf4u-advanced-function-unit-4',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mhf4u-advanced-function',
    title: 'Unit 4: Unit 4',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-gr12-school-mhf4u-advanced-function-unit-5',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mhf4u-advanced-function',
    title: 'Unit 5: Unit 5',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-gr12-school-mhf4u-advanced-function-exam',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mhf4u-advanced-function',
    title: 'Exam: Exam',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'math-gr12-school-mcv4u-calculus-vectors',
    track: 'math',
    time_block: 'grade-12',
    parent_id: null,
    title: 'School — MCV4U Calculus & Vectors (JensenMath)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 10,
  },
  {
    id: 'math-gr12-school-mcv4u-calculus-vectors-unit-1',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mcv4u-calculus-vectors',
    title: 'Unit 1: Unit 1',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-gr12-school-mcv4u-calculus-vectors-unit-2',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mcv4u-calculus-vectors',
    title: 'Unit 2: Unit 2',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-gr12-school-mcv4u-calculus-vectors-unit-3',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mcv4u-calculus-vectors',
    title: 'Unit 3: Unit 3',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-gr12-school-mcv4u-calculus-vectors-unit-4',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mcv4u-calculus-vectors',
    title: 'Unit 4: Unit 4',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-gr12-school-mcv4u-calculus-vectors-unit-5',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mcv4u-calculus-vectors',
    title: 'Unit 5: Unit 5',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-gr12-school-mcv4u-calculus-vectors-unit-6',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mcv4u-calculus-vectors',
    title: 'Unit 6: Unit 6',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'math-gr12-school-mcv4u-calculus-vectors-exam',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-school-mcv4u-calculus-vectors',
    title: 'Exam: Exam',
    resource_link: null,
    how_to_learn: null,
    sort_order: 6,
  },
  {
    id: 'math-gr12-evenings-ml-math-consolidation',
    track: 'math',
    time_block: 'grade-12',
    parent_id: null,
    title: 'Evenings — ML Math Consolidation',
    resource_link: null,
    how_to_learn: null,
    sort_order: 11,
  },
  {
    id: 'math-gr12-evenings-ml-math-consolidation-multivariate-calculus-chain-ru',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-evenings-ml-math-consolidation',
    title: 'Sept–Oct: Multivariate calculus — chain rule in matrix form, Jacobians',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-gr12-evenings-ml-math-consolidation-optimization-theory-convexity-',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-evenings-ml-math-consolidation',
    title: 'Nov–Dec: Optimization theory — convexity, saddle points, Adam/momentum math',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-gr12-evenings-ml-math-consolidation-linear-algebra-deep-dive-svd-m',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-evenings-ml-math-consolidation',
    title: 'Jan–Feb: Linear algebra deep dive — SVD, matrix factorization, spectral methods',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-gr12-evenings-ml-math-consolidation-probability-theory-formal-meas',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-evenings-ml-math-consolidation',
    title: 'Mar–Apr: Probability theory formal — measure theory lite, conjugate priors, distributions in depth',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-gr12-evenings-ml-math-consolidation-information-theory-entropy-mut',
    track: 'math',
    time_block: 'grade-12',
    parent_id: 'math-gr12-evenings-ml-math-consolidation',
    title: 'May–Jun: Information theory — entropy, mutual information, KL divergence applications',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-sa12-deep-learning-math',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Block 1: Deep Learning Math (Days 1–30)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 12,
  },
  {
    id: 'math-sa12-deep-learning-math-backprop-derivation-scalar-vec',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-deep-learning-math',
    title: '1–5: Backprop derivation — scalar → vector → matrix form',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-sa12-deep-learning-math-loss-functions-derived-mse-cro',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-deep-learning-math',
    title: '6–10: Loss functions derived — MSE, cross-entropy, KL divergence',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-sa12-deep-learning-math-activation-functions-sigmoid-t',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-deep-learning-math',
    title: '11–15: Activation functions — sigmoid, tanh, ReLU, derivatives',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-sa12-deep-learning-math-attention-mechanism-math-scale',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-deep-learning-math',
    title: '16–20: Attention mechanism math — scaled dot-product, softmax derivation',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-sa12-deep-learning-math-convolutional-math-cross-corre',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-deep-learning-math',
    title: '21–25: Convolutional math — cross-correlation, filter math',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-sa12-deep-learning-math-regularization-math-l1-l2-as-p',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-deep-learning-math',
    title: '26–30: Regularization math — L1/L2 as priors (Bayesian view), dropout',
    resource_link: null,
    how_to_learn: null,
    sort_order: 5,
  },
  {
    id: 'math-sa12-advanced-cs-math',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Block 2: Advanced CS Math (Days 31–55)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 13,
  },
  {
    id: 'math-sa12-advanced-cs-math-combinatorics-counting-generat',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-advanced-cs-math',
    title: '31–35: Combinatorics & counting — generating functions, recurrences',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-sa12-advanced-cs-math-graph-theory-trees-cycles-plan',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-advanced-cs-math',
    title: '36–40: Graph theory — trees, cycles, planarity, graph representations',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-sa12-advanced-cs-math-discrete-math-logic-sets-relat',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-advanced-cs-math',
    title: '41–45: Discrete math — logic, sets, relations, proofs',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-sa12-advanced-cs-math-number-theory-modular-arithmet',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-advanced-cs-math',
    title: '46–50: Number theory — modular arithmetic, Fermat\'s little theorem, RSA',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-sa12-advanced-cs-math-big-o-formal-asymptotic-notati',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-advanced-cs-math',
    title: '51–55: Big-O formal — asymptotic notation proofs, recurrence relations (Master theorem)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 4,
  },
  {
    id: 'math-sa12-bayesian-statistical-learning-',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Block 3: Bayesian & Statistical Learning Theory (Days 56–70)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 14,
  },
  {
    id: 'math-sa12-bayesian-statistical-learning--bayesian-ml-bayesian-linear-re',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-bayesian-statistical-learning-',
    title: '56–59: Bayesian ML — Bayesian linear regression, MAP estimation',
    resource_link: null,
    how_to_learn: null,
    sort_order: 0,
  },
  {
    id: 'math-sa12-bayesian-statistical-learning--statistical-learning-theory-bi',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-bayesian-statistical-learning-',
    title: '60–63: Statistical learning theory — bias-variance tradeoff formally, VC dimension (intro)',
    resource_link: null,
    how_to_learn: null,
    sort_order: 1,
  },
  {
    id: 'math-sa12-bayesian-statistical-learning--embedding-math-vector-spaces-c',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-bayesian-statistical-learning-',
    title: '64–67: Embedding math — vector spaces, cosine similarity derivation, why dot product works',
    resource_link: null,
    how_to_learn: null,
    sort_order: 2,
  },
  {
    id: 'math-sa12-bayesian-statistical-learning--review-fill-gaps-from-phase-7-',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: 'math-sa12-bayesian-statistical-learning-',
    title: '68–70: Review + fill gaps from Phase 7–8 coding work',
    resource_link: null,
    how_to_learn: null,
    sort_order: 3,
  },
  {
    id: 'math-sa12-ontario-school-curriculum',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'Ontario School Curriculum',
    resource_link: null,
    how_to_learn: null,
    sort_order: 15,
  },
  {
    id: 'math-sa12-ml-cs-math',
    track: 'math',
    time_block: 'summer-after-12',
    parent_id: null,
    title: 'ML/CS Math',
    resource_link: null,
    how_to_learn: null,
    sort_order: 16,
  },
];
